using UnityEngine;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using Unity.XR.CoreUtils;

public class HandsManager : MonoBehaviour
{
    /// <summary>
    /// A list of local velocities by frames, used to calculate a more stable velocity value.
    /// </summary>
    private readonly Queue<Vector3> lastNFrames = new();
    
    /// <summary>
    /// The amount of frames stored to aggregate velocity/momentum
    /// </summary>
    public const uint nFrames = 5;

    /// <summary>
    /// Position change per second, calculated as an aggregate of the last [5] frames (see nFrames).
    /// </summary>
    public Vector3 StableVelocity { get; private set; }

    [SerializeField] private InputActionProperty velocityBinding;

    private XROrigin xrOrigin;


    [Header("Settings")]
    [SerializeField][Tooltip("Determines whether to smoothen velocity over n frames or not.")] private bool smoothening = false;
    [SerializeField][Tooltip("The importance velocities newly collected have compared to other values.")] private float alpha = 0.5f;

    private void Start()
    {
        xrOrigin = FindAnyObjectByType<XROrigin>();
        if(xrOrigin == null)
        {
            Debug.LogError("Couldn't find any XR Origin objects in scene!");
        }
    }

    private void Update()
    {
        UpdateVelocity();
    }

    private void UpdateVelocity()
    {
        // if reached maximum frame buffer capacity, flush out oldest record.
        if(lastNFrames.Count == nFrames)
            lastNFrames.Dequeue();

        // read local velocity, negate xrOrigin bias, & add to buffer.
        Vector3 tempVelocity =  xrOrigin.transform.rotation * velocityBinding.action.ReadValue<Vector3>();
        lastNFrames.Enqueue(tempVelocity);

        // average over the queued velocities to get 'local' velocity/momentum.
        var tempVector = Vector3.zero;
        Queue<Vector3> copy = new(lastNFrames);

        // Implement Exponential Moving Average over last n frames (ideated together with Claude AI.
        // Claude suggested the concept of the alpha*(1-alpha)^n weighting to emulate the concept of stableVelocity = alpha * newVelocity + (1-alpha) * stableVelocity.
        // No code was generated by Claude to that effect).
        for (int i = 0; i < lastNFrames.Count; i++){
            var exp = lastNFrames.Count - i - 1;        // nFrames - i -> oldest = n-0 = n; newest = n-n = 0. -1 to accommodate for count being unreachable.
            tempVector += alpha * Mathf.Pow(1-alpha, exp) *  copy.Dequeue();
        }

        StableVelocity = smoothening ? tempVector : tempVelocity;
    }
}
